# Maps item name (lowercase) → Unsplash search keyword
# source.unsplash.com uses the keyword to find a relevant photo.
# The `sig` param (item id) keeps the same image on every reload.

KEYWORD_MAP: dict[str, str] = {
    # Fruits
    "apple": "apple fruit",
    "banana": "banana fruit",
    "mango": "mango fruit",
    "orange": "orange fruit",
    "grapes": "grapes",
    "watermelon": "watermelon",
    "papaya": "papaya fruit",
    "pineapple": "pineapple",
    "pomegranate": "pomegranate",
    "strawberry": "strawberry",
    "kiwi": "kiwi fruit",
    "guava": "guava fruit",
    "pear": "pear fruit",
    "litchi": "lychee fruit",
    "coconut": "coconut",
    # Vegetables
    "tomato": "tomato",
    "potato": "potato",
    "onion": "onion",
    "garlic": "garlic",
    "ginger": "ginger root",
    "carrot": "carrot",
    "cauliflower": "cauliflower",
    "broccoli": "broccoli",
    "spinach": "spinach",
    "capsicum": "bell pepper",
    "cucumber": "cucumber",
    "bitter gourd": "bitter gourd",
    "bottle gourd": "gourd vegetable",
    "peas": "green peas",
    "cabbage": "cabbage",
    "beans": "green beans",
    "lady finger": "okra",
    "mushroom": "mushroom",
    "sweet corn": "corn",
    "beetroot": "beetroot",
    # Grains & Staples
    "basmati rice": "rice grains",
    "whole wheat atta": "wheat flour",
    "toor dal": "lentils",
    "chana dal": "chickpea lentils",
    "moong dal": "mung beans",
    "masoor dal": "red lentils",
    "poha": "flattened rice",
    "sooji": "semolina flour",
    "maida": "white flour",
    "besan": "chickpea flour",
    "cornflour": "corn starch",
    "sugar": "sugar",
    "salt": "salt",
    # Oils & Spices
    "mustard oil": "mustard oil bottle",
    "sunflower oil": "sunflower oil",
    "coconut oil": "coconut oil jar",
    "turmeric powder": "turmeric powder",
    "red chilli powder": "red chilli powder",
    "coriander powder": "coriander spice",
    "cumin seeds": "cumin seeds",
    "mustard seeds": "mustard seeds",
    "garam masala": "spice mix",
    "chai masala": "chai spice",
    # Dairy & Eggs
    "milk": "milk glass",
    "paneer": "paneer cheese",
    "butter": "butter",
    "curd": "yogurt bowl",
    "ghee": "ghee jar",
    "eggs": "eggs",
    # Bread & Bakery
    "bread": "bread loaf",
    # Snacks
    "biscuits": "cookies biscuits",
    "namkeen": "indian snacks",
    "chips": "potato chips",
    "popcorn": "popcorn",
    "instant noodles": "noodles",
    # Condiments
    "ketchup": "ketchup tomato sauce",
    "soy sauce": "soy sauce bottle",
    "vinegar": "vinegar bottle",
    "honey": "honey jar",
    "jam": "jam jar",
    "peanut butter": "peanut butter",
    "chocolate": "chocolate",
    # Beverages
    "coffee": "coffee beans",
    "tea": "tea leaves",
    "green tea": "green tea",
    "mineral water": "water bottle",
    "cola drink": "cola drink",
    "orange juice": "orange juice",
    "coconut water": "coconut water",
    # Home Care
    "detergent powder": "laundry detergent",
    "dish soap": "dish soap",
    "floor cleaner": "cleaning products",
    "toilet cleaner": "cleaning bottle",
    "glass cleaner": "cleaning spray",
    "hand wash": "hand soap",
    # Personal Care
    "shampoo": "shampoo bottle",
    "conditioner": "hair conditioner",
    "body wash": "shower gel",
    "face wash": "face cleanser",
    "toothpaste": "toothpaste",
    "toothbrush": "toothbrush",
    "soap bar": "soap bar",
    "deodorant": "deodorant",
    "shaving cream": "shaving cream",
    "sunscreen": "sunscreen lotion",
    "lip balm": "lip balm",
    # Paper & Baby
    "tissue box": "tissue box",
    "toilet paper": "toilet paper",
    "cotton buds": "cotton buds",
    "sanitary pads": "feminine hygiene",
    "diapers": "baby diapers",
    # Electronics
    "usb keyboard": "mechanical keyboard",
    "wireless mouse": "computer mouse",
    "hdmi cable": "hdmi cable",
    "usb hub": "usb hub",
    "phone charger": "phone charger",
    "usb-c cable": "usb cable",
    "earphones": "earphones",
    "bluetooth speaker": "bluetooth speaker",
    "power bank": "power bank",
    "screen protector": "smartphone screen",
    "phone cover": "phone case",
    "selfie stick": "selfie stick",
    # Home & Stationery
    "led bulb": "led light bulb",
    "extension board": "power strip",
    "aa batteries": "batteries",
    "duct tape": "duct tape",
    "sticky notes": "sticky notes",
    "ball pen": "pen writing",
    "stapler": "stapler",
    "scissors": "scissors",
}


def get_image_url(name: str, item_id: int, size: int = 400) -> str:
    keyword = KEYWORD_MAP.get(name.lower(), name.lower())
    keyword_encoded = keyword.replace(" ", "%20")
    return f"https://source.unsplash.com/{size}x{size}/?{keyword_encoded}&sig={item_id}"
